name: Lint Go Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    # !!! ЭТО РЕШЕНИЕ !!!
    # Устанавливаем рабочую директорию по умолчанию для всех шагов ниже.
    # Все команды будут выполняться так, как будто мы сначала сделали 'cd ./forge'.
    defaults:
      run:
        working-directory: ../

    steps:
      # Шаг 1: Скачиваем весь репозиторий.
      # Этот шаг не зависит от defaults и всегда работает в корне.
      - name: Checkout Code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Go.
      # Благодаря 'defaults', этот шаг будет запущен в папке './forge'
      # и правильно найдет go.mod для кеширования.
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          cache: true
          # Указываем путь к go.mod для надежного кеширования
          cache-dependency-path: ../go.sum


      # Шаг 3: Запускаем линтер.
      # Он также унаследует 'working-directory' из 'defaults'
      # и запустится в правильном контексте без ошибок.
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          # Мы больше не указываем working-directory здесь, так как он задан глобально.