name: Forge CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.4

      - name: Check formatting
        run: |
          test -z "$(gofmt -l .)" || (echo "Go code is not formatted" && exit 1)

        # запускаем тесты (на будущее)

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.2
          working-directory: ./

      - name: Build
        run: |
          go build -v ./cmd/forge
          go build -v ./cmd/forged

