name: Lint Go Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Скачиваем ваш код в рабочую среду CI
      - name: Checkout Code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем правильную версию Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Убедитесь, что эта версия совпадает с той, что в вашем go.mod
          go-version: '1.24.4'

      # Шаг 3: (КРИТИЧЕСКИ ВАЖНЫЙ) Скачиваем все зависимости
      # Эта команда читает ваш go.mod и go.sum и загружает все пакеты.
      - name: Download Go modules
        run: go mod download

      # Шаг 4: Запускаем линтер (теперь он найдет все пакеты)
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          # Этот action умный и сам найдет go.mod,
          # а кеширование зависимостей (шаг 3) уже произошло.